services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.1
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama,nomic-embed-text,llama3.2'
      CLUSTER_HOSTNAME: 'node1'

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD:-redis_password}" ]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

#  celery_worker:
#    image: python:3.10-slim
#    volumes:
#      - ..:/app
#    working_dir: /app
#    command: >
#      bash -c "pip install -r requirements.txt &&
#             celery -A app.celery_app worker --loglevel=info"
#    environment:
#      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
#      - REDIS_SERVER=redis
#      - REDIS_PORT=${REDIS_PORT:-6379}
#      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
#      - REDIS_USER=${REDIS_USER}
#      - MYSQL_HOST=mysql
#      - MYSQL_PORT=${MYSQL_PORT:-3306}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#    depends_on:
#      - redis
#
#  api:
#    volumes:
#      - ..:/app
#    working_dir: /app
#    image: python:3.10-slim
#    ports:
#      - "8000:8000"
#    command: >
#      bash -c "pip install -r requirements.txt &&
#             python -m app.main"
#    environment:
#      - MYSQL_HOST=mysql
#      - MYSQL_PORT=${MYSQL_PORT:-3306}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      # Redis
#      - REDIS_SERVER=redis
#      - REDIS_PORT=${REDIS_PORT:-6379}
#      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
#      - REDIS_USER=${REDIS_USER}
#    depends_on:
#      - mysql
#      - redis
#      - celery_worker

volumes:
  mysql_data:
  weaviate_data:
  redis_data:
