name: Deploy Sphinx documentation to Pages

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'docs/**/*'
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  pages:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python_version: ${{ matrix.python-version }}
    - id: deployment
      name: Build Documentation
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/sphinx_doc/source
        python_version: ${{ matrix.python-version }}
        publish: false
        requirements_path: ./docs/sphinx_doc/requirements.txt
    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: SphinxDoc
        path: ${{ steps.deployment.outputs.artifact }}
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}