name: Generate TOC
on:
  push:
    paths: ['README.md']

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "## ðŸ“‘ Table of Contents"
          CREATE_PR: false
          TARGET_PATHS: "README.md"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}